BEGIN

INSERT INTO W14_ROUND (ID, NAME)
VALUES (1, 'Group Stage');

INSERT INTO W14_ROUND (ID, NAME)
VALUES (8, 'Round of 32');

INSERT INTO W14_ROUND (ID, NAME)
VALUES (2, 'Round of 16');

INSERT INTO W14_ROUND (ID, NAME)
VALUES (3, 'Quarter-Finals');

INSERT INTO W14_ROUND (ID, NAME)
VALUES (4, 'Semi-Finals');

INSERT INTO W14_ROUND (ID, NAME)
VALUES (5, 'Final(3 & 4)');

INSERT INTO W14_ROUND (ID, NAME)
VALUES (6, 'Final');

COMMIT;
END;