BEGIN

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (1, 'Algeria', 1, 'image/svg', 'algeria.svg', 'DZ');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (2, 'Argentina', 1, 'image/svg', 'argentina.svg', 'AR');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (3, 'Australia', 1, 'image/svg', 'australia.svg', 'AU');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (4, 'Austria', 1, 'image/svg', 'austria.svg', 'AT');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (5, 'Belgium', 1, 'image/svg', 'belgium.svg', 'BE');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (6, 'Bosnia and Herzegovina', 1, 'image/svg', 'bosnia and herzegovina.svg', 'BA');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (7, 'Brazil', 1, 'image/svg', 'brazil.svg', 'BR');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (8, 'Canada', 1, 'image/svg', 'canada.svg', 'CA');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (9, 'Cape Verde', 1, 'image/svg', 'cape verde.svg', 'CV');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (10, 'Colombia', 1, 'image/svg', 'colombia.svg', 'CO');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (11, 'Croatia', 1, 'image/svg', 'croatia.svg', 'HR');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (12, 'Curaçao', 1, 'image/svg', 'curacao.svg', 'CW');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (13, 'Czechia', 1, 'image/svg', 'czechia.svg', 'CZ');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (14, 'Congo', 1, 'image/svg', 'congo.svg', 'CD');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (15, 'Ecuador', 1, 'image/svg', 'ecuador.svg', 'EC');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (16, 'Egypt', 1, 'image/svg', 'egypt.svg', 'EG');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (17, 'England', 1, 'image/svg', 'england.svg', 'GB-EN');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (18, 'France', 1, 'image/svg', 'france.svg', 'FR');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (19, 'Germany', 1, 'image/svg', 'germany.svg', 'DE');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (20, 'Ghana', 1, 'image/svg', 'ghana.svg', 'GH');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (21, 'Haiti', 1, 'image/svg', 'haiti.svg', 'HT');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (22, 'Iran', 1, 'image/svg', 'iran.svg', 'IR');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (23, 'Iraq', 1, 'image/svg', 'iraq.svg', 'IQ');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (24, 'Ivory Coast', 1, 'image/svg', 'ivory coast.svg', 'CI');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (25, 'Japan', 1, 'image/svg', 'japan.svg', 'JP');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (26, 'Jordan', 1, 'image/svg', 'jordan.svg', 'JO');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (27, 'Mexico', 1, 'image/svg', 'mexico.svg', 'MX');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (28, 'Morocco', 1, 'image/svg', 'morocco.svg', 'MA');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (29, 'Netherlands', 1, 'image/svg', 'netherlands.svg', 'NL');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (30, 'New Zealand', 1, 'image/svg', 'new zealand.svg', 'NZ');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (31, 'Norway', 1, 'image/svg', 'norway.svg', 'NO');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (32, 'Panama', 1, 'image/svg', 'panama.svg', 'PA');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (33, 'Paraguay', 1, 'image/svg', 'paraguay.svg', 'PY');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (34, 'Portugal', 1, 'image/svg', 'portugal.svg', 'PT');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (35, 'Qatar', 1, 'image/svg', 'qatar.svg', 'QA');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (36, 'Saudi Arabia', 1, 'image/svg', 'saudi arabia.svg', 'SA');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (37, 'Scotland', 1, 'image/svg', 'scotland.svg', 'GB-SCT');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (38, 'Senegal', 1, 'image/svg', 'senegal.svg', 'SN');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (39, 'South Africa', 1, 'image/svg', 'south africa.svg', 'ZA');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (40, 'Korea Republic', 1, 'image/svg', 'korea republic.svg', 'KR');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (41, 'Spain', 1, 'image/svg', 'spain.svg', 'ES');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (42, 'Sweden', 1, 'image/svg', 'sweden.svg', 'SE');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (43, 'Switzerland', 1, 'image/svg', 'switzerland.svg', 'CH');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (44, 'Tunisia', 1, 'image/svg', 'tunisia.svg', 'TN');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (45, 'Turkey', 1, 'image/svg', 'turkey.svg', 'TR');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (46, 'Uruguay', 1, 'image/svg', 'uruguay.svg', 'UY');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (47, 'USA', 1, 'image/svg', 'usa.svg', 'US');

INSERT INTO W14_TEAM (ID, NAME, TOURNAMENT_TYPE_ID, IMAGE_MIME_TYPE, IMAGE_FILE_NAME, IMG_CODE)
VALUES (48, 'Uzbekistan', 1, 'image/svg', 'uzbekistan.svg', 'UZ');

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (49, '{A_2}', 'Runner-up of Group A', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (50, '{B_2}', 'Runner-up of Group B', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (51, '{E_1}', 'Winner of Group E', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (52, '{ABCDF_3}', 'Best 3rd place from Groups A, B, C, D or F', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (53, '{F_1}', 'Winner of Group F', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (54, '{C_2}', 'Runner-up of Group C', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (55, '{C_1}', 'Winner of Group C', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (56, '{F_2}', 'Runner-up of Group F', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (57, '{I_1}', 'Winner of Group I', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (58, '{CDFGH_3}', 'Best 3rd place from Groups C, D, F, G or H', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (59, '{E_2}', 'Runner-up of Group E', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (60, '{I_2}', 'Runner-up of Group I', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (61, '{A_1}', 'Winner of Group A', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (62, '{CEFHI_3}', 'Best 3rd place from Groups C, E, F, H or I', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (63, '{L_1}', 'Winner of Group L', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (64, '{EHIJK_3}', 'Best 3rd place from Groups E, H, I, J or K', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (65, '{D_1}', 'Winner of Group D', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (66, '{BEFIJ_3}', 'Best 3rd place from Groups B, E, F, I or J', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (67, '{G_1}', 'Winner of Group G', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (68, '{AEHIJ_3}', 'Best 3rd place from Groups A, E, H, I or J', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (69, '{K_2}', 'Runner-up of Group K', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (70, '{L_2}', 'Runner-up of Group L', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (71, '{H_1}', 'Winner of Group H', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (72, '{J_2}', 'Runner-up of Group J', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (73, '{B_1}', 'Winner of Group B', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (74, '{EFGIJ_3}', 'Best 3rd place from Groups E, F, G, I or J', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (75, '{J_1}', 'Winner of Group J', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (76, '{H_2}', 'Runner-up of Group H', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (77, '{K_1}', 'Winner of Group K', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (78, '{DEIJL_3}', 'Best 3rd place from Groups D, E, I, J or L', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (79, '{D_2}', 'Runner-up of Group D', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (80, '{G_2}', 'Runner-up of Group G', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (81, '{W_74}', 'Winner of Match 74', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (82, '{W_77}', 'Winner of Match 77', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (83, '{W_73}', 'Winner of Match 73', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (84, '{W_75}', 'Winner of Match 75', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (85, '{W_76}', 'Winner of Match 76', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (86, '{W_78}', 'Winner of Match 78', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (87, '{W_79}', 'Winner of Match 79', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (88, '{W_80}', 'Winner of Match 80', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (89, '{W_83}', 'Winner of Match 83', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (90, '{W_84}', 'Winner of Match 84', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (91, '{W_81}', 'Winner of Match 81', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (92, '{W_82}', 'Winner of Match 82', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (93, '{W_86}', 'Winner of Match 86', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (94, '{W_88}', 'Winner of Match 88', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (95, '{W_85}', 'Winner of Match 85', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (96, '{W_87}', 'Winner of Match 87', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (97, '{W_89}', 'Winner of Match 89', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (98, '{W_90}', 'Winner of Match 90', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (99, '{W_93}', 'Winner of Match 93', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (100, '{W_94}', 'Winner of Match 94', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (101, '{W_91}', 'Winner of Match 91', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (102, '{W_92}', 'Winner of Match 92', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (103, '{W_95}', 'Winner of Match 95', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (104, '{W_96}', 'Winner of Match 96', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (105, '{W_97}', 'Winner of Match 97', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (106, '{W_98}', 'Winner of Match 98', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (107, '{W_99}', 'Winner of Match 99', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (108, '{W_100}', 'Winner of Match 100', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (109, '{L_101}', 'Loser of Match 101', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (110, '{L_102}', 'Loser of Match 102', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (111, '{W_101}', 'Winner of Match 101', 1);

INSERT INTO W14_TEAM (ID, NAME, COMMENT_, TOURNAMENT_TYPE_ID)
VALUES (112, '{W_102}', 'Winner of Match 102', 1);

COMMIT;
END;