BEGIN

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (27, 1);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (40, 1);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (39, 1);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (13, 1);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (8, 2);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (43, 2);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (35, 2);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (6, 2);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (7, 3);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (28, 3);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (37, 3);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (21, 3);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (47, 4);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (33, 4);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (3, 4);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (45, 4);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (19, 5);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (15, 5);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (24, 5);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (12, 5);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (29, 6);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (25, 6);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (44, 6);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (42, 6);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (5, 9);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (22, 9);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (16, 9);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (30, 9);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (41, 10);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (46, 10);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (36, 10);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (9, 10);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (18, 11);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (38, 11);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (31, 11);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (23, 11);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (2, 12);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (4, 12);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (1, 12);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (26, 12);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (34, 13);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (10, 13);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (48, 13);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (14, 13);

INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (17, 14);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (11, 14);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (32, 14);
INSERT INTO W14_TEAM_TEAMGROUP (TEAM_ID, TEAMGROUP_ID)
VALUES (20, 14);

COMMIT;
END;