BEGIN

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (1, 'Group A', 'A');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (2, 'Group B', 'B');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (3, 'Group C', 'C');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (4, 'Group D', 'D');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (5, 'Group E', 'E');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (6, 'Group F', 'F');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (9, 'Group G', 'G');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (10, 'Group H', 'H');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (11, 'Group I', 'I');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (12, 'Group J', 'J');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (13, 'Group K', 'K');

INSERT INTO W14_TEAMGROUP (ID, NAME, SHORTNAME)
VALUES (14, 'Group L', 'L');

COMMIT;
END;